//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGestorCodigo.DM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BBDD : DbContext
    {
        public BBDD()
            : base("name=BBDD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorias> categoriasSet { get; set; }
        public virtual DbSet<codigos> codigosSet { get; set; }
        public virtual DbSet<departamentos> departamentosSet { get; set; }
        public virtual DbSet<codigo_categoria> codigo_categoria { get; set; }
        public virtual DbSet<carpetas> carpetas { get; set; }
        public virtual DbSet<notas> notas { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<ultimo_inicio> ultimo_inicio { get; set; }
        public virtual DbSet<carpetas_contrasenas> carpetas_contrasenas { get; set; }
        public virtual DbSet<notas_compartidas> notas_compartidas { get; set; }
        public virtual DbSet<contrasenas> contrasenas { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<GrupoUsuario> GrupoUsuario { get; set; }
        public virtual DbSet<PasswordDepartamento> PasswordDepartamento { get; set; }
        public virtual DbSet<PasswordGrupo> PasswordGrupo { get; set; }
        public virtual DbSet<PasswordUsuario> PasswordUsuario { get; set; }
        public virtual DbSet<HerramientaExterna> HerramientaExterna { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Query_VerPasswordCompartidas(Nullable<int> idUsuarios)
        {
            var idUsuariosParameter = idUsuarios.HasValue ?
                new ObjectParameter("idUsuarios", idUsuarios) :
                new ObjectParameter("idUsuarios", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Query_VerPasswordCompartidas", idUsuariosParameter);
        }
    }
}
