//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGestorCodigo.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class carpetas
    {
        public int idCarpeta { get; set; }
        public string nombreCarpeta { get; set; }
        public Nullable<int> fk_IdCarpetaPadre { get; set; }
        public Nullable<int> fk_IdUsuario { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    }
}
