//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGestorCodigo.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorias
    {
        public int idCategoria { get; set; }
        public string nombreCategoria { get; set; }
        public string descripcionCategoria { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    }
}
