//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGestorCodigo.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class codigos
    {
        public int idCodigo { get; set; }
        public string nombreCodigo { get; set; }
        public string descripcion { get; set; }
        public string codigo { get; set; }
        public int fk_IdAutor { get; set; }
        public Nullable<int> fk_Idcarpeta { get; set; }
        public System.DateTime fechaModificacion { get; set; }
        public int fk_IdUsuarioUltimaModificacion { get; set; }
    }
}
