//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGestorCodigo.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordUsuario
    {
        public int idPasswordUsuario { get; set; }
        public Nullable<int> idPassword { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    }
}
